#!/usr/bin/perl -w

use strict;

my @msg = <STDIN>;

open(LOG, ">>TESTING-PENEMO") or die "couldnt open file: $!";
	print LOG "this is what I got from the command line parameters:\n";
	print LOG @msg;
	print LOG "\n--end--\n";
close LOG;

exit;
